import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import React from "react";
import { Sidebar } from "../components/sidebar";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto({
	subsets: ["latin"],
	weight: ["900", "700", "500", "400", "300", "100"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<ThemeProvider attribute="class" defaultTheme="dark">
					<Sidebar />
					{children}
					<Toaster position="top-center" />
				</ThemeProvider>
			</body>
		</html>
	);
}
