export const metadata = {
	title: 'Doa Sehari hari',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<div >
			<div>{children}</div>
		</div>
	)
}
